tf-bucket-path: clusters-google/
tf-cloud-provider: google
folder-prefix: perf

enable-impersonation-multinode: true
pxf-jvm-opts: "-Xmx512m -Xms512m"
perf-ccp-reap-minutes: 120

perf-gpdb-number-of-nodes: 3
perf-gpdb-segments-per-host: 4
perf-gpdb-instance-type: n1-standard-4

perf-hadoop-number-of-nodes: 3
perf-hadoop-initialization-script: gs://pxf-perf/scripts/load-lineitem-dataset.sh
perf-hadoop-instance-type: n1-standard-4

perf-trigger-interval: 24h
perf-trigger-start: 12:30 PM
perf-trigger-stop: 12:40 PM
